### ISSUE TITLE
Throwing an error

### ISSUE THREAD

**Issue by RJCooLEST** [galaxy119/AdminTools#10]
![image](https://user-images.githubusercontent.com/56374469/90207961-3b157780-de1a-11ea-8783-e67f38d0d769.png)

**Comment by RJCooLEST** [comment]
This message will appear when I check each plugin again. So I mistakenly thought that there was a problem here.

I know this may not be a problem with this plugin, it is not intended to disturb.....

**Comment by galaxy119** [comment]
This is not a problem with Admin Tools.
